apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  containers: elasticsearch
  version: 7.6.2
  nodeSets:
  - name: default
    env:
    - name: ES_JAVA_OPTS
      value: -Xms512m -Xmx512m
    resources:
      requests:
        memory: 512Mi
        cpu: 0.5
      limits:
        memory: 512Mi
        cpu: 1
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
